src/Entity/Student.php
<?php

namespace App\Entity;

use App\Repository\StudentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StudentRepository::class)
 */
class Student
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity=User::class, inversedBy="profile", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=AcademicLevel::class, inversedBy="students")
     */
    private $academicLevel;

    /**
     * @ORM\OneToMany(targetEntity=StudentCourse::class, mappedBy="student")
     */
    private $studentCourses;

    /**
     * @ORM\OneToMany(targetEntity=StudentContentReaction::class, mappedBy="student")
     */
    private $studentContentReactions;

    /**
     * @ORM\OneToMany(targetEntity=StudentChapter::class, mappedBy="student", orphanRemoval=true)
     */
    private $studentChapters;

    /**
     * @ORM\OneToMany(targetEntity=StudentQuestion::class, mappedBy="student")
     */
    private $studentQuestions;

    /**
     * @ORM\OneToMany(targetEntity=StudentQuiz::class, mappedBy="student")
     */
    private $studentQuizzes;

    /**
     * @ORM\OneToMany(targetEntity=QuestionAnswer::class, mappedBy="student")
     */
    private $questionAnswers;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $student_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $profilePicture;

    /**
     * @ORM\Column(type="boolean")
     */
    private $profileUpdated;

    public function __construct()
    {
        $this->studentCourses = new ArrayCollection();
        $this->studentContentReactions = new ArrayCollection();
        $this->studentChapters = new ArrayCollection();
        $this->studentQuestions = new ArrayCollection();
        $this->studentQuizzes = new ArrayCollection();
        $this->questionAnswers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getAcademicLevel(): ?AcademicLevel
    {
        return $this->academicLevel;
    }

    public function setAcademicLevel(?AcademicLevel $academicLevel): self
    {
        $this->academicLevel = $academicLevel;

        return $this;
    }

    /**
     * @return Collection|StudentCourse[]
     */
    public function getStudentCourses(): Collection
    {
        return $this->studentCourses;
    }

    public function addStudentCourse(StudentCourse $studentCourse): self
    {
        if (!$this->studentCourses->contains($studentCourse)) {
            $this->studentCourses[] = $studentCourse;
            $studentCourse->setStudent($this);
        }

        return $this;
    }

    public function removeStudentCourse(StudentCourse $studentCourse): self
    {
        if ($this->studentCourses->removeElement($studentCourse)) {
            // set the owning side to null (unless already changed)
            if ($studentCourse->getStudent() === $this) {
                $studentCourse->setStudent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|StudentContentReaction[]
     */
    public function getStudentContentReactions(): Collection
    {
        return $this->studentContentReactions;
    }

    public function addStudentContentReaction(StudentContentReaction $studentContentReaction): self
    {
        if (!$this->studentContentReactions->contains($studentContentReaction)) {
            $this->studentContentReactions[] = $studentContentReaction;
            $studentContentReaction->setStudent($this);
        }

        return $this;
    }

    public function removeStudentContentReaction(StudentContentReaction $studentContentReaction): self
    {
        if ($this->studentContentReactions->removeElement($studentContentReaction)) {
            // set the owning side to null (unless already changed)
            if ($studentContentReaction->getStudent() === $this) {
                $studentContentReaction->setStudent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|StudentChapter[]
     */
    public function Cs(): Collection
    {
        return $this->studentChapters;
    }

    public function addStudentChapter(StudentChapter $studentChapter): self
    {
        if (!$this->studentChapters->contains($studentChapter)) {
            $this->studentChapters[] = $studentChapter;
            $studentChapter->setStudent($this);
        }

        return $this;
    }

    public function removeStudentChapter(StudentChapter $studentChapter): self
    {
        if ($this->studentChapters->removeElement($studentChapter)) {
            // set the owning side to null (unless already changed)
            if ($studentChapter->getStudent() === $this) {
                $studentChapter->setStudent(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        // return $this->getUser();
        return $this->user->getFirstName()." ".$this->user->getMiddleName()." ".$this->user->getLastName();
    }

    /**
     * @return Collection|StudentQuestion[]
     */
    public function getStudentQuestions(): Collection
    {
        return $this->studentQuestions;
    }

    public function addStudentQuestion(StudentQuestion $studentQuestion): self
    {
        if (!$this->studentQuestions->contains($studentQuestion)) {
            $this->studentQuestions[] = $studentQuestion;
            $studentQuestion->setStudent($this);
        }

        return $this;
    }

    public function removeStudentQuestion(StudentQuestion $studentQuestion): self
    {
        if ($this->studentQuestions->removeElement($studentQuestion)) {
            // set the owning side to null (unless already changed)
            if ($studentQuestion->getStudent() === $this) {
                $studentQuestion->setStudent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|StudentQuiz[]
     */
    public function getStudentQuizzes(): Collection
    {
        return $this->studentQuizzes;
    }

    public function addStudentQuiz(StudentQuiz $studentQuiz): self
    {
        if (!$this->studentQuizzes->contains($studentQuiz)) {
            $this->studentQuizzes[] = $studentQuiz;
            $studentQuiz->setStudent($this);
        }

        return $this;
    }

    public function removeStudentQuiz(StudentQuiz $studentQuiz): self
    {
        if ($this->studentQuizzes->removeElement($studentQuiz)) {
            // set the owning side to null (unless already changed)
            if ($studentQuiz->getStudent() === $this) {
                $studentQuiz->setStudent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|QuestionAnswer[]
     */
    public function getQuestionAnswers(): Collection
    {
        return $this->questionAnswers;
    }

    public function addQuestionAnswer(QuestionAnswer $questionAnswer): self
    {
        if (!$this->questionAnswers->contains($questionAnswer)) {
            $this->questionAnswers[] = $questionAnswer;
            $questionAnswer->setStudent($this);
        }

        return $this;
    }

    public function removeQuestionAnswer(QuestionAnswer $questionAnswer): self
    {
        if ($this->questionAnswers->removeElement($questionAnswer)) {
            // set the owning side to null (unless already changed)
            if ($questionAnswer->getStudent() === $this) {
                $questionAnswer->setStudent(null);
            }
        }

        return $this;
    }

    public function getStudentId(): ?string
    {
        return $this->student_id;
    }

    public function setStudentId(string $student_id): self
    {
        $this->student_id = $student_id;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profilePicture;
    }

    public function setProfilePicture(?string $profilePicture): self
    {
        $this->profilePicture = $profilePicture;

        return $this;
    }

    public function getProfileUpdated(): ?bool
    {
        return $this->profileUpdated;
    }

    public function setProfileUpdated(bool $profileUpdated): self
    {
        $this->profileUpdated = $profileUpdated;

        return $this;
    }

    public function getAllFields()
    {
        return get_object_vars($this);
    }
}

src/Entity/UserType.php
<?php

namespace App\Entity;

use App\Repository\UserTypeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserTypeRepository::class)
 */
class UserType
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=User::class, mappedBy="userType")
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity=Help::class, mappedBy="usertype")
     */
    private $helps;

   

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->helps = new ArrayCollection();
     }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setUserType($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            // set the owning side to null (unless already changed)
            if ($user->getUserType() === $this) {
                $user->setUserType(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getAllFields()
    {
        return get_object_vars($this);
    }

    /**
     * @return Collection|Help[]
     */
    public function getHelps(): Collection
    {
        return $this->helps;
    }

    public function addHelp(Help $help): self
    {
        if (!$this->helps->contains($help)) {
            $this->helps[] = $help;
            $help->setUsertype($this);
        }

        return $this;
    }

    public function removeHelp(Help $help): self
    {
        if ($this->helps->removeElement($help)) {
            // set the owning side to null (unless already changed)
            if ($help->getUsertype() === $this) {
                $help->setUsertype(null);
            }
        }

        return $this;
    }

    
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use App\Entity\AcademicLevel;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;


class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstName')
            ->add('middleName')
            ->add('lastName')
            ->add('sex' ,ChoiceType::class,[
                'required' => true,
                'attr'=>['class'=>'form-control'],
                'choices'  => [
                    'Male' => "m",
                    'Female' => "f",
                 ],
            ])
            ->add('userType',null, [
                'required' => true,
            ])
            ->add('email', EmailType::class, [
                'required' => true,
            ])
            ->add('academicLevel', EntityType::class, [
                'mapped' => false,
                'class' => AcademicLevel::class,
                'choice_label' => 'name',
                'attr' => ['class' => 'form-control mb-3', 'disabled' => 'disabled'],
            ])
            // ->add('username')
            // ->add('password')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-danger">{% trans %}Delete{% endtrans %}</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
{{ form_errors(form) }}

<div class="row ">
	<div class="form-group  col-md-4 col-sm-6 ">
		{{form_label(form.firstName,'First Name' | trans | raw)  }}
		{{ form_widget(form.firstName,{'attr':{'class':form_errors(form.firstName)? 'form-control is-invalid':'form-control','placeholder':" Enter first name"|trans}}) }}
		<div class="help-block text-danger">{{form_errors(form.firstName)}}</div>
	</div>
	<div class="form-group col-md-4 col-sm-6 ">
		{{form_label(form.middleName,'Middle Name' | trans | raw)}}
		{{ form_widget(form.middleName,{'attr':{'class':form_errors(form.middleName)? 'form-control is-invalid':'form-control','placeholder':" Enter middle name"|trans}}) }}
		<div class="help-block text-danger">{{form_errors(form.middleName)}}</div>
	</div>
	<div class="form-group  col-md-4 col-sm-6 ">
		{{form_label(form.lastName,'Last Name' | trans | raw)}}
		{{ form_widget(form.lastName,{'attr':{'class':form_errors(form.lastName)? 'form-control is-invalid':'form-control','placeholder':" Enter last name"|trans}}) }}
		<div class="help-block text-danger">{{form_errors(form.lastName)}}</div>
	</div>

</div><br>
<div class="row">
	<div class="col-md-6">
		<div class="form-group ">
			{{form_label(form.email,'Email' | trans | raw)}}
			{{ form_widget(form.email,{'attr':{'class':form_errors(form.email)? 'form-control  is-invalid':'form-control ','placeholder':" Enter username"|trans}}) }}
			<div class="help-block text-danger">{{form_errors(form.email)}}</div>
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group ">
			{{form_label(form.sex)}}
			{{ form_widget(form.sex,{'attr':{'class':form_errors(form.sex)? 'form-control  is-invalid':'form-control '}}) }}
			<div class="help-block text-danger">{{form_errors(form.sex)}}</div>
		</div>
	</div>
</div><br>
<div class="row">
	<div class="col-md-6">
		<div class="form-group ">
			{{form_label(form.userType,'User Type' | trans | raw)}}
			{{ form_widget(form.userType,{'attr':{'class':form_errors(form.userType)? 'form-control  is-invalid':'form-control ','placeholder':"Enter..."}}) }}
			<div class="help-block text-danger">{{form_errors(form.userType)}}</div>
		</div>
	</div>
	{% if edit == false %}
		<div class="col-md-6" id="academicLevel" style="display:none">
			<div class="form-group ">
				{{form_label(form.academicLevel,'academic level' | trans | raw)}}
				{{ form_widget(form.academicLevel,{'attr':{'class':form_errors(form.academicLevel)? 'form-control  is-invalid':'form-control'}}) }}
				<div class="help-block text-danger">{{form_errors(form.academicLevel)}}</div>
			</div>
		</div>
		{% else %}
		<div class="col-md-6" id="academiscLevel" style="display:none">
			<div class="form-group ">
				{{form_label(form.academicLevel,'academic level' | trans | raw)}}
				{{ form_widget(form.academicLevel,{'attr':{'class':form_errors(form.academicLevel)? 'form-control  is-invalid':'form-control'}}) }}
				<div class="help-block text-danger">{{form_errors(form.academicLevel)}}</div>
			</div>
		</div>
	{% endif %}
</div><input type="hidden" name="userid" value="{{edit}}"></div><div class="col-md-6"></div><div class="card-footer float-right"><table>
<td>
	<button class="btn  btn-success save">{{ button_label|default('Save') | trans | raw }}</button>
	<button class="buttonload btn btn-primary" id="spinner" style="display:none">
		<i class="fa fa-spinner fa-spin"></i>
		Signing Up
	</button>
</td>
<td>
	<a href="{{app.request.headers.get('referer')}}" class="btn btn-info ">{% trans %}Back{% endtrans %}</a>
</td></table></div></div>{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Edit User{% endtrans %}{% endblock %}
{% block breadcrumbhome %}
    <a href="{{ path('user_index') }} ">
	   {% trans %}User{% endtrans %} 
	</a> 
{% endblock %}
{% block breadcrumbcontent %}{% trans %}Edit{% endtrans %}{% endblock %}
{% block body %}
    <h1>{% trans %}Edit User{% endtrans %}</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}">{% trans %}Back to list{% endtrans %}</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/new.html.twig
{% extends 'security/login.html.twig' %}
{% block breadcrumbhome %}
    <a href="{{ path('user_index') }} ">
	   {% trans %}User{% endtrans %} 
	</a> 
{% endblock %}
{% block breadcrumbcontent %}{% trans %}New{% endtrans %}{% endblock %}
{% block fullbody %}
	<div class="row">
		<div class="card col-8 m-auto">
			<div class="card-body login-card-body">
				<p class="login-box-msg">{% trans %}Create Adminstrator Account{% endtrans %}</p>

				{{ include('user/_form.html.twig') }}
			</div>
		</div>


	</>
{% endblock %}
{% block javascripts %}
	<script>
		$(function () { // Initialize Select2 Elements
$('.select2').select2()

// Initialize Select2 Elements
$('.select2bs4').select2({theme: 'bootstrap4'})
$('#dteofBirth').datepicker({format: 'mm-dd-yyyy'})
});
	</script>

{% endblock %}

templates/user/password.html.twig
{% extends 'security/login.html.twig' %}

{% block body %}
 <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">{% trans %}You are only one step a way from your new password now{% endtrans %}.</p>
{{ form_start(form,{'attr': {'role':'form'}}) }}

		 <div class="input-group mb-3">
		 {{ form_widget(form.newPassword.first,{'attr':{'class':'form-control','placeholder':'New password'}}) }}
       
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
					{{ form_widget(form.newPassword.second,{'attr':{'class':'form-control','placeholder':'Confirm password'}}) }}

        
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">{% trans %}Change password{% endtrans %}</button>
          </div>
          <!-- /.col -->
        </div>
	
			







{{ form_end(form) }}
        
    </div>
    <!-- /.login-card-body -->
  </div



	
{% endblock %}

templates/user/print.html.twig
<!doctype html>
<html lang="en">

	<head>
		<title>:: {% trans %}Print{% endtrans %} ::</title>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">


		<link
		rel="icon" href="favicon.ico" type="image/x-icon">
		<!-- VENDOR CSS -->
		<link rel="stylesheet" href="{{ asset('assets/vendor/bootstrap/css/bootstrap.min.css') }}">
		<link
		rel="stylesheet" href="{{ asset('assets/vendor/font-awesome/css/font-awesome.min.css') }}">

		<!-- MAIN CSS -->
		<link rel="stylesheet" href="{{ asset('assets/css/main.css') }}">
		<link rel="stylesheet" href="{{ asset('assets/css/color_skins.css') }}">
	</head>

	<body
		class="theme-cyan">
		<!-- WRAPPER -->
		<div id="wrapper">
			<div class="vertical-align-wrap">
				<div class="vertical-align-middle auth-main">
					<div class="auth-box">
						<div class="top"></div>
						<div class="card">
							<div class="header">
								<p class="lead">{% trans %}Credentials{% endtrans %}</p>
                                <ul class="header-dropdown">
				<li>
					<a href="javascript:void(0);" onclick="window.print();">
						<i class="icon-printer"></i>
					</a>
				</li>
			</ul>
							</div>
							<div class="body">
								{% block body %}

							
									<p>
									 
									<hr>
									<small class="text-muted">Password:
								{% trans %}{% endtrans %}</small>
									<p>
										{{ password }}</p>
									<hr>


								{% endblock %}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- END WRAPPER -->
	</body>
</html>

templates/user/profile.html.twig
{% extends "sBase.html.twig" %}
{% block stylesheet %}
	<link rel="stylesheet" href="{{asset('student/css/theme-elements.css')}}">
   <style>
      section.section{
         padding: 10px;
      }
   </style>
{% endblock %}
{% block body %}
	<div class="container pt-3 pb-2">
		<div class="card">
			<div class="card-header">
				<h4>
					<center>Profile</center>
				</h4>
			</div>
			<div class="card-body" style="padding: 30px">
				<div class="row pt-2">
					<div class="col-lg-3 mt-4 mt-lg-0">
						{{ form_start(form) }}
						<div class="d-flex justify-content-center mb-4">
							<div class="profile-image-outer-container">
								<div class="profile-image-inner-container bg-color-primary">
									{% if user.profile.profilePicture %}
										<img src="/uploads/profileImages/{{ user.profile.profilePicture }}" id="uploadPreview">
									{% else %}
										<img src="/images/blank-image.png" id="uploadPreview">
									{% endif %}
									<span class="profile-image-button bg-color-dark">
										<i class="fas fa-camera text-light"></i>
									</span>
								</div>
								{{ form_widget(form.profilePicture) }}
							</div>
						</div>
					</div>
					<div class="col-lg-9">
						{% if profile_updated %}
							<div class="form-group row">
								<label class="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2 ">ID</label>
								<div class="col-lg-9 has-success">
									<b>{{ user.profile.studentId }}</b>
								</div>
							</div>
							<div class="form-group row">
								<label class="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2 ">First name</label>
								<div class="col-lg-9 has-success">
									<b>{{ user.firstName }}</b>
								</div>
							</div>
							<div class="form-group row">
								<label class="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2 ">Middle name</label>
								<div class="col-lg-9 has-success">
									<b>{{ user.middleName }}</b>
								</div>
							</div>
							<div class="form-group row">
								<label class="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2 ">Last Name</label>
								<div class="col-lg-9 has-success">
									<b>{{	user.lastName }}</b>
								</div>
							</div>
						{% else %}
							<p>** You have only one chance to update your name. so please check and approve carefully **</p>
							{{ form_errors(form) }}
							<div class="form-group row">
								<label class="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2 required">First name</label>
								<div class="col-lg-9 has-success">
									{{	form_widget(form.firstName) }}
								</div>
							</div>
							<div class="form-group row">
								<label class="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2 required">Middle name</label>
								<div class="col-lg-9 has-success">
									{{	form_widget(form.middleName) }}
								</div>
							</div>
							<div class="form-group row">
								<label class="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2 required">Last Name</label>
								<div class="col-lg-9 has-success">
									{{	form_widget(form.lastName) }}
								</div>
							</div>
						{% endif %}
							<div class="form-group row">
								<label class="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2">Email</label>
								<div class="col-lg-9">
									{{	form_widget(form.email) }}
								</div>
							</div>

                     <br>
							<div class="form-group col-lg-12">
							{% if profile_updated %}
								<input type="submit" value="Save" class="btn btn-primary btn-modern float-end" data-loading-text="Loading...">
							{% else %}
								<input type="submit" value="Approve" id="approve" class="btn btn-primary btn-modern float-end" data-loading-text="Loading...">
							{% endif %}
							</div>
							{{ form_end(form) }}
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

</div>{% endblock %}

{% block javascript %}
	<script>
		function readURL(input) {
			if (input.files && input.files[0]) {
				var reader = new FileReader();

				reader.onload = function (e) {
						$('#uploadPreview').attr('src', e.target.result);
				}

				reader.readAsDataURL(input.files[0]);
			}
		}

		$("#profile_profilePicture").change(function(){
			readURL(this);
		});

		$("#profile_type2_profilePicture").change(function(){
			readURL(this);
		});

		
	</script>
{% endblock %}

templates/user/reset.html.twig
{% extends 'security/login.html.twig' %}

{% block body %}
	<div class="card">
		<div class="card-body login-card-body">
			<p class="login-box-msg">{% trans %}You forgot your password? Here you can easily retrieve a new password.{% endtrans %}</p>
			{% for label, messages in app.flashes %}
				{% for message in messages %}
					<div class="row alert alert-{{ label }} alert-dismissible">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
						<h4 class="mr-4">
							<i class="icon fa fa-{% if label=='success' %}check {% else %}ban {% endif %}"></i>
							{% trans %}Alert{% endtrans %}!</h4>
						{{ message }}

					</div>


				{% endfor %}
			{% endfor %}
      {% if form is defined %}
      
			{{ form_start(form,{'attr': {'role':'form'}}) }}


			<div class="input-group mb-3">
				{{ form_widget(form.username,{'attr':{'class':'form-control','placeholder':'Username'}}) }}


				<div class="input-group-append">
					<div class="input-group-text">
						<span class="fas fa-user"></span>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-12">
					<button type="submit" class="btn btn-primary btn-block">{% trans %}Request new password{% endtrans %}</button>
				</div>
				<!-- /.col -->
			</div>

			{{ form_end(form) }}
{% endif %}
			<p class="mt-3 mb-1">
				<a href="{{ path('app_login')}}" class="nav-link">{% trans %}Login{% endtrans %}</a>
			</p>

		</div>
		<!-- /.login-card-body -->
	</div>


{% endblock %}